# _config.yml

title: Duckist
description: 'I am Md Musfiqur Rahman Jehad. A professional web developer'

# Site settings
baseurl: '' # The subpath of your site, e.g., /blog
url: 'https://duckist.me' # The base hostname & protocol for your site
repository: 'https://github.com/duckist/duckist.github.io' # Repository URL
theme: jekyll-theme-minimal-mistakes

# Build settings
markdown: kramdown
highlighter: rouge

# Minimal Mistakes settings
minimal_mistakes_skin: 'default'
minimal_mistakes_remote_theme:
  url: 'https://github.com/mmistakes/minimal-mistakes.git'
  branch: 'main'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# GitHub Pages
github:
  is_project_page: false
  enable_emoji: true

# Jekyll SEO
seo:
  name: 'Duckist'
  social:
    - name: 'twitter'
      url: 'https://twitter.com/duckisr'
    - name: 'linkedin'
      url: 'https://linkedin.com/in/duckist'
    - name: 'github'
      url: 'https://github.com/duckist'

